### ISSUE TITLE
Tests failed on Xamarin TC

### ISSUE THREAD

**Issue by kkokologos** [xamarinhq/test-cloud-appium-java-extensions#11]
Hi, I followed the steps for configuration test cloud for Appium test, but the tests are not executing on TC. I think that the issue is related to the pom.xml that is generated after performing "mvn -DskipTests -P prepare-for-upload package". For more details see the attached pom.xml file.

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building run-test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ run-test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ run-test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ run-test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ run-test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ run-test ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ run-test ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: target/run-test-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (default) @ run-test ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ run-test ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[pom.xml.txt](https://github.com/xamarinhq/test-cloud-appium-java-extensions/files/1044608/pom.xml.txt)

**Comment by marjanSterjev** [comment]
What is the purpose of the effective pom in the upload directory? How is it related to the other artifacts (dependency classes and compiled test classes) in the same folder? How are tests executed on TC, using Maven? This kind of information could be useful in order to figure out where the problem is.

**Comment by john7doe** [comment]
marjan (and kkokologos),

The effective pom contains a complete the list of dependencies. Without the effective pom we would be unable to determine the dependencies when users are using parent pom's. The test are executed using Maven.

The best way for me to help you is if you can provide a link to the failing tests. Br,
/Simon

**Comment by madeboga** [comment]
i am facing issue detail image below. Anything solution for this issue? need help. Thanks
<img width="1048" alt="banners_and_alerts_and_com_cimbx_lifestyle-app_-_sep_8__2017_2_00_55_pm_-_xamarin_test_cloud" src="https://user-images.githubusercontent.com/25861575/30207762-c8a97eae-94ba-11e7-96e0-3622037d0315.png">

**Comment by john7doe** [comment]
The best thing for you is to reach out to testcloud-support@xamarin.com and they will help you resolve the issue.
