### ISSUE TITLE
XTC Commands not recognized while Uploading via XTC CLI - Command Line Interface

### ISSUE THREAD

**Issue by ShivaCsk5557** [xamarinhq/test-cloud-appium-java-extensions#12]
Hi Team,
 	We, @Mindtree Ltd., Bangalore INDIA are trying to automate one of our mobile applications through XTC command line interface and we followed the below link’s instructions:
https://github.com/xamarinhq/test-cloud-appium-java-extensions
 	We are currently stuck at performing cloud upload where we use those xtc commands. We followed downloading the xtc zip file and extracted (though we didn’t any see option to unlock as mentioned). And when we try to open command window from the xtc folder, the result is same as below: Not recognized command
 
 	Please help us run xtc commands and how to make them recognizable. We will reply with more info once we hear from you.

![xtc commands not recognised](https://user-images.githubusercontent.com/32518791/32043615-e1c7a46a-ba58-11e7-9754-162b98f45fb8.png)

**Comment by john7doe** [comment]
you need to make sure that the folder with the xtc file/command is on the PATH.

**Comment by ShivaCsk5557** [comment]
Hey John,
I am working on an WIndows machine and as per this below link. It is not required to add PATH variable for xtc. 
https://github.com/xamarinhq/test-cloud-appium-java-extensions/blob/master/UploaderInstall.md/#installation 
Leaving aside this fact, 
## i tried adding the file path in PATH but still same error. Please help.
![xtc commands not recognised after path](https://user-images.githubusercontent.com/32518791/32064459-8ac21c24-ba97-11e7-8e7b-fab054a316d9.png)
