### ISSUE TITLE
driver.label() does not work locally

### ISSUE THREAD

**Issue by Lagoja** [xamarinhq/test-cloud-appium-java-extensions#2]
*Issue:*

Tests fail when run locally with screenshots using `driver.label()`. After some debugging, I realized this is because `System.getenv("PWD)` is null when I launch IntelliJ from Applications. 

If I launch IntelliJ from bash, `System.getenv("PWD)` will take the PWD of the directory where I launched IntelliJ. So when I launched from `/Applications`, the test passes, but all the screenshots are left in my Applications folder

![unspecified](https://cloud.githubusercontent.com/assets/750845/17827255/9abb9bfa-662e-11e6-9dd7-f9103907401a.png)

*Desired Behavior:*

1. Instead of using `PWD` we should either leave the pngs in the tempdir, or drop them in a relative path from the test source. I'm not sure how this works in Test Cloud.
1. `driver.label()` must work regardless of where the user launches their IDE.

**Comment by skovsboll** [comment]
Thanks for reporting this, @Lagoja. I agree, your bullets were both design goals that we wanted to meet. 
Still some work to be done here.
