### ISSUE TITLE
Document version of jUnit supported

### ISSUE THREAD

**Issue by krukow** [xamarinhq/test-cloud-appium-java-extensions#3]
I accidentally tried with jUnit 4.11 - in which case you get a 

`java.lang.NoClassDefFoundError: org/junit/AssumptionViolatedException`

we should document that jUnit 4.12 must be used

**Comment by Lagoja** [comment]
Is there also a requirement on the Appium Java Client? I think I had to switch to version 4.1.1 in order to use these ectensions

**Comment by john7doe** [comment]
We now support 4.9 and higher and it is now documented in the README
